packages:
  - client
  - backend

ignoredBuiltDependencies:
  - puppeteer

onlyBuiltDependencies:
  - '@firebase/util'
  - '@swc/core'
  - '@whiskeysockets/baileys'
  - esbuild
  - protobufjs
  - re2
  - sharp
